# -*- coding: utf-8 -*-
"""T5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlROM_dsw4SAH8717S4m5pX9yLmDtxJw

LIBRARY
"""

!pip install experta

!pip install --upgrade frozendict

"""SISTEM PAKAR DIAGNOSIS PENYAKIT DENGAN EXPERTA"""

from experta import *

class Diagnosis(KnowledgeEngine):

    @Rule(Fact(cough=True), Fact(fever=True), Fact(fatigue=True))
    def flu(self):
        print("Diagnosis: Kamu terkena flu")

    @Rule(Fact(cough=True), Fact(fever=True), Fact(breathing_difficulty=True))
    def pneumonia(self):
        print("Diagnosis: Kamu terkena pneumonia")

    @Rule(Fact(sneezing=True), Fact(runny_nose=True), Fact(cough=False))
    def cold(self):
        print("Diagnosis: Kamu terkena cold")

    @Rule(Fact(sore_throat=True), Fact(fever=True))
    def throat_infection(self):
        print("Diagnosis: Kamu terkena throat infection")

    # Penyakit tambahan:
    @Rule(Fact(fever=True), Fact(cough=True), Fact(fatigue=True), Fact(loss_of_smell=True))
    def covid(self):
        print("Diagnosis: Kamu kemungkinan terkena COVID-19")

    @Rule(Fact(sneezing=True), Fact(itchy_eyes=True), Fact(stuffy_nose=True))
    def allergy(self):
        print("Diagnosis: Kamu mengalami alergi")

    @Rule(Fact(persistent_cough=True), Fact(weight_loss=True), Fact(long_fever=True))
    def tuberculosis(self):
        print("Diagnosis: Kamu terkena TBC (Tuberkulosis)")

    @Rule(Fact(high_fever=True), Fact(joint_pain=True), Fact(skin_rash=True))
    def dengue(self):
        print("Diagnosis: Kamu terkena DBD (Demam Berdarah Dengue)")

    @Rule(Fact(cough=False), Fact(fever=False), Fact(fatigue=False),
          Fact(breathing_difficulty=False), Fact(sneezing=False), Fact(runny_nose=False),
          Fact(sore_throat=False), Fact(loss_of_smell=False), Fact(itchy_eyes=False),
          Fact(stuffy_nose=False), Fact(persistent_cough=False), Fact(weight_loss=False),
          Fact(long_fever=False), Fact(high_fever=False), Fact(joint_pain=False),
          Fact(skin_rash=False))
    def healthy(self):
        print("Diagnosis: Kamu sehat")

def get_input():
    def ask(question):
        return input(question + " (yes/no): ").strip().lower() == "yes"

    return {
        "cough": ask("Apakah kamu batuk?"),
        "fever": ask("Apakah kamu demam?"),
        "fatigue": ask("Apakah kamu merasa lelah?"),
        "breathing_difficulty": ask("Apakah kamu mengalami kesulitan bernapas?"),
        "sneezing": ask("Apakah kamu bersin-bersin?"),
        "runny_nose": ask("Apakah kamu mengalami hidung berair?"),
        "sore_throat": ask("Apakah kamu sakit tenggorokan?"),
        "loss_of_smell": ask("Apakah kamu kehilangan indra penciuman?"),
        "itchy_eyes": ask("Apakah kamu merasa mata gatal?"),
        "stuffy_nose": ask("Apakah kamu mengalami hidung tersumbat?"),
        "persistent_cough": ask("Apakah kamu batuk berkepanjangan?"),
        "weight_loss": ask("Apakah kamu mengalami penurunan berat badan?"),
        "long_fever": ask("Apakah kamu mengalami demam berkepanjangan?"),
        "high_fever": ask("Apakah kamu mengalami demam tinggi?"),
        "joint_pain": ask("Apakah kamu merasakan nyeri sendi?"),
        "skin_rash": ask("Apakah kamu memiliki bintik merah di kulit?")
    }

if __name__ == "__main__":
    print("Selamat datang di Sistem Pakar Diagnosis Penyakit.\nSilakan jawab pertanyaan berikut:")
    symptoms = get_input()
    engine = Diagnosis()
    engine.reset()

    for symptom, value in symptoms.items():
        engine.declare(Fact(**{symptom: value}))

    engine.run()

"""SISTEM PAKAR MEDIS INTERAKTIF DENGAN DETEKSI MULTI-PENYAKIT"""

from experta import *

class SistemPakarMedis(KnowledgeEngine):
    @Rule(Fact(demam=True), Fact(batuk=True))
    def flu(self):
        print("Diagnosis: Kamu terkena flu")

    @Rule(Fact(sakit_tenggorokan=True), Fact(demam=True))
    def throat_infection(self):
        print("Diagnosis: Kamu terkena infeksi tenggorokan")

    @Rule(Fact(nyeri_otot=True), Fact(nyeri_perut=True))
    def hernia(self):
        print("Diagnosis: Kamu terkena hernia")

    # Penyakit tambahan
    @Rule(Fact(demam=True), Fact(batuk=True), Fact(kelelahan=True), Fact(hilang_penciuman=True))
    def covid(self):
        print("Diagnosis: Kemungkinan besar kamu terkena COVID-19")

    @Rule(Fact(bersin=True), Fact(hidung_tersumbat=True), Fact(mata_gatal=True))
    def alergi(self):
        print("Diagnosis: Kamu mengalami alergi")

    @Rule(Fact(batuk_berkepanjangan=True), Fact(penurunan_bb=True), Fact(demam_berminggu=True))
    def tbc(self):
        print("Diagnosis: Kamu terkena TBC (Tuberkulosis)")

    @Rule(Fact(demam_tinggi=True), Fact(nyeri_sendi=True), Fact(bintik_merah=True))
    def dbd(self):
        print("Diagnosis: Kamu terkena DBD (Demam Berdarah Dengue)")

    @Rule(Fact(
        demam=False, batuk=False, sakit_tenggorokan=False,
        nyeri_otot=False, nyeri_perut=False, kelelahan=False,
        hilang_penciuman=False, bersin=False, hidung_tersumbat=False,
        mata_gatal=False, batuk_berkepanjangan=False, penurunan_bb=False,
        demam_berminggu=False, demam_tinggi=False, nyeri_sendi=False, bintik_merah=False
    ))
    def sehat(self):
        print("Diagnosis: Kamu sehat")

def tanya_gejala():
    def tanya(pertanyaan):
        return input(f"{pertanyaan} (yes/no): ").strip().lower() == "yes"

    return {
        "demam": tanya("Apakah kamu demam?"),
        "batuk": tanya("Apakah kamu batuk?"),
        "sakit_tenggorokan": tanya("Apakah kamu sakit tenggorokan?"),
        "nyeri_otot": tanya("Apakah kamu nyeri otot?"),
        "nyeri_perut": tanya("Apakah kamu nyeri perut?"),
        "kelelahan": tanya("Apakah kamu merasa kelelahan?"),
        "hilang_penciuman": tanya("Apakah kamu kehilangan penciuman?"),
        "bersin": tanya("Apakah kamu sering bersin?"),
        "hidung_tersumbat": tanya("Apakah kamu mengalami hidung tersumbat?"),
        "mata_gatal": tanya("Apakah kamu merasa mata gatal?"),
        "batuk_berkepanjangan": tanya("Apakah kamu batuk berkepanjangan?"),
        "penurunan_bb": tanya("Apakah kamu kehilangan berat badan secara drastis?"),
        "demam_berminggu": tanya("Apakah kamu demam lebih dari seminggu?"),
        "demam_tinggi": tanya("Apakah kamu mengalami demam tinggi?"),
        "nyeri_sendi": tanya("Apakah kamu mengalami nyeri sendi?"),
        "bintik_merah": tanya("Apakah kamu memiliki bintik merah pada kulit?")
    }

if __name__ == "__main__":
    print("=== Sistem Pakar Medis ===")
    print("Silakan jawab pertanyaan berikut:")
    gejala = tanya_gejala()

    engine = SistemPakarMedis()
    engine.reset()

    for nama, nilai in gejala.items():
        engine.declare(Fact(**{nama: nilai}))

    engine.run()